/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.e;

import javax.swing.JCheckBox;

/**
 *
 * @author edmon
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        lblerror.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnote = new javax.swing.JScrollPane();
        txtnotes = new javax.swing.JTextArea();
        btnstart = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcheckbox1.setText("I've read all of the above");
        txtcheckbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckbox1ActionPerformed(evt);
            }
        });

        txtnotes.setColumns(20);
        txtnotes.setRows(5);
        txtnotes.setText("Welcome to the CEATA CALCULATOR\n-Please READ ALL showed ABOVE before Starting the Calculator app\n-In this program you will be able to access to 4 different types of Calculators.\n-The First Function of this app would be able to help with sorting your changes.\n\n-The Second Function of this app would be able to help with adding up your changes.\n\n-The Third Function of this app would be able to help with Subtracting your Money \nwith the cost and see how much Change you have left.\n\n-The Fourth Function of this app would be able to help with averaging up your spends/changes\n\n-In this app 3 different math methods are being used for better user experience,\nthey are Math.round, Math.addExact, and Math.subtractExact.\n\n-There are few Custom Methods I used, most of them are related to my math methods, and\nthe most important ones are the disappear method which makes my lables disappear when\nthe app start, and make them show again when the user clicks a button. \n");
        txtnote.setViewportView(txtnotes);

        btnstart.setText("BACK");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitle.setText("CEATA CALCULATOR");

        txtcheckbox2.setText("I've understanded what the app is for");

        lblerror.setText("Please select all checkboxes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lbltitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtnote, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnstart)
                        .addGap(33, 33, 33)
                        .addComponent(lblerror))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(txtcheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtcheckbox2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnote, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcheckbox1)
                .addGap(3, 3, 3)
                .addComponent(txtcheckbox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstart)
                    .addComponent(lblerror))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtcheckbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckbox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcheckbox1ActionPerformed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        // When click the "back" button returns to the main page
        //check if all checkboxes are clicked
        boolean understood = true;
        for (int i = 0; i < 2; i++) {
            if (!checkBoxList[i].isSelected()) {
                understood = false;
            }
        }
        if (understood) {
            U1A1_EdmondLiang myFrame1 = new U1A1_EdmondLiang();
            myFrame1.setVisible((true));
            this.dispose();
        }
        else {
            lblerror.setVisible(true);
        }
        
    }//GEN-LAST:event_btnstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lbltitle;
    private static final javax.swing.JCheckBox txtcheckbox1 = new javax.swing.JCheckBox();
    private static final javax.swing.JCheckBox txtcheckbox2 = new javax.swing.JCheckBox();
    private javax.swing.JScrollPane txtnote;
    private javax.swing.JTextArea txtnotes;
    // End of variables declaration//GEN-END:variables
    static JCheckBox[] checkBoxList = {txtcheckbox1, txtcheckbox2};


}
